#pragma once

#include <Arduino.h>

enum EventType : uint16_t
{
  WIFI_CONNECTING = 1,
  WIFI_CONNECTED,
  WIFI_CONNECT_FAILED,
  WIFI_DISCONNECTED,

  MQTT_SERVER_CONNECTED,
  MQTT_SERVER_DISCONNECTED,
  MQTT_SERVER_CONNECT_FAILED,
  
  SERIAL_DATA,

  I2C_HUB_CONNECTED,
  I2C_HUB_ERROR,

  PORTB_HUB_CONNECTED,
  PORTB_HUB_ERROR,

  ENCODER_1_CONNECTED,
  ENCODER_1_ERROR,
  ENCODER_1_DATA,

  FLOW_SENSOR_1_CONNECTED,
  FLOW_SENSOR_1_DATA,

  THERMOCOUPLE_CONNECTED,
  THERMOCOUPLE_ERROR,
  THERMOCOUPLE_DATA,

  ANGLE_SENSOR_1_DATA,
  ANGLE_SENSOR_2_DATA,

  CONDUCT_SENSOR_DATA,

  UI_REQUEST_CALIBRATION,

  DEBUG_MESSAGE
};