{
 "title": "MOSTR Dashboard",
 "time": { "from": "2025-03-29T22:03:05.473Z", "to": "2025-04-30T09:05:48.541Z" },
 "templating": {
  "list": [
   { "name": "device_id", "label": "Stirrer Device ID", "query": "analytics_bioreactor_01" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 14, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n  <strong style=\"font-size: 3em;\">Stirred Tank</strong>\r\n</div>"
   }
  },
  {
   "title": "Panel Title",
   "type": "canvas",
   "gridPos": { "h": 20, "w": 14, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) =>\r\n    r[\"entity_id\"] == \"${device_id}_flow_rate\" or\r\n    r[\"entity_id\"] == \"${device_id}_flow_rate_2\" or\r\n    r[\"entity_id\"] == \"${device_id}_water_conductivity\" or\r\n    r[\"entity_id\"] == \"${device_id}_water_temperature\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"friendly_name\", \"entity_id\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean_pivot\")"
    }
   ]
  },
  {
   "title": "Water Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"${device_id}_water_temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Water Conductivity (ms/cm)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 30 },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"${device_id}_water_conductivity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Stirrer (rpm)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"${device_id}_flow_rate_2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Input Flow Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"${device_id}_flow_rate\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}